# Summary 

Logistic regression analysis is used to study predictors of domestic violence victimization using the Public Safety Survey 2009 data. 

Gender, age in years, educational level, non-domestic violent victimization and crime problem in respondent’s neighbourhood are used as independent variables in the analysis, and the following hypotheses are made:

_H1 Women are more likely to have experienced domestic violence than men._

_H2 Young people are more likely to have experienced domestic violence than the old._

_H3 Less educated people are more likely to have experienced domestic violence._

_H4 Those who have experienced other than domestic violence are more likely to have experienced domestic violence as well._

_H5 Serious crime problem in one’s neighbourhood increases the risk of having experienced domestic violence._

After conducting the analysis, all the hypotheses except H3 are verified. Women are almost four times more likely to have experienced domestic violence than men. Young people are more likely to have experienced more domestic violence than the old. Educational level is not a statistically significant predictor of domestic violence. Those who have experienced other than domestic violence are almost 18 times more likely to have experienced domestic violence as well. Serious crime problem in one’s neighbourhood increases the risk of having experienced domestic violence by 1,7.

However, the results of testing the logistic regression model show that statistically the model is quite useless in predicting domestic violence. This is caused by the very low proportion of respondents who had experienced domestic violence.
